LibraryTask/Models/ErrorViewModel.cs
using System;

namespace LibraryTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryTask/Controllers/BookController.cs
using AutoMapper;
using BL;
using BL.Models;
using BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryTask.Controllers
{
    public class BookController : Controller
    {
        private IUnitOfWork unitOfWork;
        private readonly IMapper mapper;
        private readonly IToastNotification toastNotification;

        public BookController(IUnitOfWork _unitOfWork , IMapper mapper , IToastNotification toastNotification)
        {
            this.unitOfWork = _unitOfWork;
            this.mapper = mapper;
            this.toastNotification = toastNotification;
        }

        public IActionResult GetAll()
        {
            var data = unitOfWork.Books.GetAll().ToList();
            var result = mapper.Map<List<BookVM>>(data);
            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(BookVM _book)
        {
            if (ModelState.IsValid)
            {
                var book = mapper.Map<Book>(_book);
                unitOfWork.Books.Add(book);
                unitOfWork.Complete();
                toastNotification.AddSuccessToastMessage("Book Created Successfully");
                return RedirectToAction("GetAll");
            }
            else
            {
                return View(_book);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var book = unitOfWork.Books.GetById(id);
            var Book = mapper.Map<BookVM>(book);

            return View(Book);
        }

        [HttpPost]
        public IActionResult Edit(BookVM model)
        {
            if(ModelState.IsValid)
            {
                var book = mapper.Map<Book>(model);
                unitOfWork.Books.Update(book);
                unitOfWork.Complete();
                toastNotification.AddSuccessToastMessage("Book Updated Successfully");
                return RedirectToAction("GetAll");
            }

            return View(model);
        }

    }
}

LibraryTask/Controllers/BorrowedBooksController.cs
using AutoMapper;
using BL;
using BL.Models;
using BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryTask.Controllers
{
    public class BorrowedBooksController : Controller
    {

        private IUnitOfWork unitOfWork;
        private readonly IMapper mapper;
        public BorrowedBooksController(IUnitOfWork _unitOfWork, IMapper mapper)
        {
            this.unitOfWork = _unitOfWork;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var data = unitOfWork.Borrowers.GetAll().ToList();
            var AllBorrowers = mapper.Map<List<BorrowerVM>>(data);
            ViewBag.AllBorrowers = new SelectList(AllBorrowers, "Id", "Name");
            return View();
        }
        //الكتب التى تم استعارتها من قبل اليوزر
        public IActionResult bookbyborrower(int id)
        {
            var data = unitOfWork.BorrowedBooks.GetAll().Where(a => a.BorrowerId == id).Include(a=>a.Book).ToList();
            return PartialView(data);
        }
        //الكتب المتاحه للاستعاره
        public IActionResult Availablebooks(int id)
        {
            var data = new List<Book>();
            var data2 = unitOfWork.BorrowedBooks.GetAll().Where(a => a.BorrowerId == id).Include(a => a.Book).ToList();
            foreach (var item in data2)
            {
                data.Add(item.Book);
            };

            var data3 = unitOfWork.Books.GetAll().Where(a => a.Number > 0).ToList();

             IEnumerable<Book> differenceQuery = data3.Except(data);

            return PartialView(differenceQuery);
        }
        //ايعاده الكتاب الى المكتبه وزياده العدد واحد
        public IActionResult returnBook(int id)
        {
            var book = unitOfWork.BorrowedBooks.GetById(id);
            var bookid = book.BookId;
            unitOfWork.BorrowedBooks.Delete(book.Id);
            //
            var b = unitOfWork.Books.GetById(bookid);
            b.Number = b.Number + 1;
            unitOfWork.Books.Update(b);
            unitOfWork.Complete();
            //

            return Ok();
        }

        //استعاره الكتاب من المكتبه وانقاص العدد واحد
        public IActionResult borrowBook(int bookId , int borrowerid)
        {
            var book = new BorrowedBooksVM() { BookId = bookId, BorrowerId = borrowerid };
            var b = mapper.Map<BorrowedBooks>(book);
            unitOfWork.BorrowedBooks.Add(b);
            //
            var Book = unitOfWork.Books.GetById(bookId);
            Book.Number = Book.Number - 1;
            unitOfWork.Books.Update(Book);
            unitOfWork.Complete();
            //

            return Ok();
        }


    }
}

LibraryTask/Controllers/BorrowerController.cs
using AutoMapper;
using BL;
using BL.Models;
using BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryTask.Controllers
{
    public class BorrowerController : Controller
    {

        private IUnitOfWork unitOfWork;
        private readonly IMapper mapper;
        private readonly IToastNotification toastNotification;

        public BorrowerController(IUnitOfWork _unitOfWork, IMapper mapper , IToastNotification toastNotification)
        {
            this.unitOfWork = _unitOfWork;
            this.mapper = mapper;
            this.toastNotification = toastNotification;
        }

        public IActionResult GetAll()
        {
            var data = unitOfWork.Borrowers.GetAll().ToList();
            var result = mapper.Map<List<BorrowerVM>>(data);
            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(BorrowerVM _Borrower)
        {
            if (ModelState.IsValid)
            {
                var b = mapper.Map<Borrower>(_Borrower);
                unitOfWork.Borrowers.Add(b);
                unitOfWork.Complete();
                toastNotification.AddSuccessToastMessage("Borrower Created Successfully");
                return RedirectToAction("GetAll");
            }
            else
            {
                return View(_Borrower);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var borrower = unitOfWork.Borrowers.GetById(id);
            var data = mapper.Map<BorrowerVM>(borrower);

            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(BorrowerVM model)
        {
            if (ModelState.IsValid)
            {
                var borrower = mapper.Map<Borrower>(model);
                unitOfWork.Borrowers.Update(borrower);
                unitOfWork.Complete();
                toastNotification.AddSuccessToastMessage("Borrower Updated Successfully");
                return RedirectToAction("GetAll");
            }

            return View(model);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryTask/Controllers/HomeController.cs
using LibraryTask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryTask/Views/Book/Add.cshtml
@model BL.ViewModels.BookVM

@{
    ViewData["Title"] = "Add";
}

<h1>Add New Book</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryTask/Views/Book/Edit.cshtml
@model BL.ViewModels.BookVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit the Book</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryTask/Views/Book/GetAll.cshtml
@model IEnumerable<BL.ViewModels.BookVM>

@{
    ViewData["Title"] = "GetAll";
}

<h1 class="text-center">All Books</h1>

<p class="text-center my-2">
    <a asp-action="Add" class="btn btn-success">Create New Book</a>
</p>
<table class="table text-center table-hover">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id } , new { @class = "btn btn-info"}) 
            </td>
        </tr>
}
    </tbody>
</table>

LibraryTask/Views/BorrowedBooks/Availablebooks.cshtml
@model IEnumerable<BL.Models.Book>

    <h3 class="text-center">Available books</h3>
<hr />
@if (Model.Count() == 0)
{
    <div class="alert alert-success text-center">
        <h5>There are no books currently available for this customer</h5>
    </div>
}
else
{
    <table class="table table-hover text-center">
        <thead class="table-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td>
                        <button id="return" onclick="Borrow(@item.Id)" class="btn btn-success">Borrow the book</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>  
    }

LibraryTask/Views/BorrowedBooks/Index.cshtml
@{
    ViewData["Title"] = "Index";
}



<div class="form-group w-50 mx-auto text-center">
    <label class="control-label mx-auto"> Choose the customer</label>
    <select id="boid" asp-items="ViewBag.AllBorrowers" class="form-control">
        <option>---Choose the customer---</option>
    </select>
</div>

<div id="d1">

</div>

<div id="d2">

</div>

@section Scripts{
    <script>
        function getid() {
            let id = $("#boid").val();
            $("#d1").load("/BorrowedBooks/bookbyborrower/" + id);
            $("#d2").load("/BorrowedBooks/Availablebooks/" + id)
        };
        $("#boid").on("change", function () {

            getid();
        })
        function save(id) {
            $.ajax({
                    url: '/BorrowedBooks/returnBook/' + id,
                success: function () {
                    getid();
                    toastr.success('The book has been successfully returned to the library');
                    
                },

                error: function () {
                    toastr.error('Something went wrong!');
                }
                })
        }
        function Borrow(id) {
            let Id = $("#boid").val();
            $.ajax({
                url: '/BorrowedBooks/borrowBook',
                data: { bookId: id, borrowerid : Id},
                success: function () {
                    getid();
                    toastr.success('The book has been successfully borrowed');
                },
                error: function () {
                    toastr.error('Something went wrong!');
                }
            })
        }
    </script>
}

LibraryTask/Views/BorrowedBooks/bookbyborrower.cshtml
@model IEnumerable<BL.Models.BorrowedBooks>

    <h3 class="text-center">Borrowed books</h3>
<hr />
@if (Model.Count() == 0)
{
    <div class="alert alert-success text-center">
        <h5>This customer has not borrowed any books yet</h5>
    </div>
}
else
{
    <table class="table text-center table-hover">
        <thead class="table-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Book.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Book.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Book.Author)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Book.Author)
                    </td>
                    <td>
                        <button id="return" onclick="save(@item.Id)" class="btn btn-danger">Return the book</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

LibraryTask/Views/Borrower/Add.cshtml
@model BL.ViewModels.BorrowerVM

@{
    ViewData["Title"] = "Add";
}

<h1>Add New Borrower</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryTask/Views/Borrower/Edit.cshtml
@model BL.ViewModels.BorrowerVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Borrower</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryTask/Views/Borrower/GetAll.cshtml
@model IEnumerable<BL.ViewModels.BorrowerVM>

@{
    ViewData["Title"] = "GetAll";
}

<h1 class="text-center">All Borrowers</h1>

<p class="text-center my-2">
    <a asp-action="Add" class="btn btn-success">Create New Borrower</a>
</p>
<table class="table text-center  table-hover">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id }, new { @class = "btn btn-info" })
            </td>
        </tr>
}
    </tbody>
</table>

LibraryTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LibraryTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="GetAll">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrower" asp-action="GetAll">Borrowers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BorrowedBooks" asp-action="Index">BorrowedBooks</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibraryTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>